modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="luluocean"
version="0.0.1-1.20.1"
displayName="Project Minequatica"
authors="Lulu Borealis"
description='''A private mod used by Lulu for her friends.\nIt is a catchall mod that helps create an aquatic paradise.'''
[[dependencies.luluocean]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    side="BOTH"
[[dependencies.luluocean]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luluocean]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.1.6,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.luluocean]]
    modId="corgilib"
    mandatory=true
    versionRange="[4.0.1.1,)"
    ordering="NONE"
    side="BOTH"